/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import assignment.Buyer;
import assignment.Item;
import assignment.MyReader;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author xxhackerxx
 */
public class BuyerFrame extends javax.swing.JFrame {

    private Buyer buyer;

    public BuyerFrame(Buyer buyer) {
        this.buyer = buyer;
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewItemsOnSale = new javax.swing.JButton();
        purchaseItem = new javax.swing.JButton();
        viewRecords = new javax.swing.JButton();
        updateDetails = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        welcomeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trading System");
        setLocation(new java.awt.Point(380, 180));
        setPreferredSize(new java.awt.Dimension(507, 387));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        viewItemsOnSale.setText("View items on sale");
        viewItemsOnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemsOnSaleActionPerformed(evt);
            }
        });

        purchaseItem.setText("Purchase an item");
        purchaseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseItemActionPerformed(evt);
            }
        });

        viewRecords.setText("View own bought items");
        viewRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRecordsActionPerformed(evt);
            }
        });

        updateDetails.setText("Update account details");
        updateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDetailsActionPerformed(evt);
            }
        });

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(purchaseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(viewRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(viewItemsOnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(purchaseItem, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewItemsOnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewItemsOnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemsOnSaleActionPerformed
        BuyerViewItemOnSale view = new BuyerViewItemOnSale(buyer);
        this.setVisible(false);
        view.setVisible(true);
    }//GEN-LAST:event_viewItemsOnSaleActionPerformed

    private void purchaseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseItemActionPerformed
        if (MyReader.getAvailableItems().size() > 0) {
//            BuyerPurchaseItem b = new BuyerPurchaseItem(buyer);
//            this.setVisible(false);
//            b.setVisible(true);
            ArrayList<Item> items = MyReader.getAvailableItems();

            JFrame frame = new JFrame();
            frame.setMinimumSize(new Dimension(800, 600));

            JPanel panel = new JPanel(new GridLayout(items.size(), 2, 5, 5));

            for (Item item : items) {
                JLabel iconLabel = new JLabel();
                iconLabel.setSize(400, 250);
                String file = item.getItemFile();
                if (file.equals("")) {
                    iconLabel.setText("<html><div style='text-align: center;'> No Preview Available</div></html>");
                    iconLabel.setHorizontalAlignment(SwingConstants.CENTER);
                } else {
                    iconLabel.setIcon(ResizeImage(file, iconLabel));
                }
                iconLabel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
                panel.add(iconLabel);

                JLabel txt = new JLabel();
                txt.setText("<html>" + " =================================================" + "<br>" + "Item title: " + item.getItemTitle() + "<br>" + " Item Describtion: " + item.getItemDescribtion() + "<br>" + " Item Price: " + "RM " + item.getItemPrice() + "<br>" + " Item Category: " + item.getItemCategory() + "<br>" + " Method of delivery: " + item.getMethodOfDelivery() + "<br>" + " =================================================" + "<br>" + "</html>");
                panel.add(txt);
            }

            JScrollPane scr = new JScrollPane(panel);
            frame.add(scr, BorderLayout.CENTER);
            frame.setLocationRelativeTo(null);
            frame.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No avaliable Items to be bought", "No Items", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_purchaseItemActionPerformed

    public ImageIcon ResizeImage(String ImagePath, JLabel lab) {
        ImageIcon MyImage = new ImageIcon(ImagePath);
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(lab.getWidth(), lab.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }

    private void viewRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRecordsActionPerformed
        BuyerViewOwnBoughtRecords view = new BuyerViewOwnBoughtRecords(buyer);
        this.setVisible(false);
        view.setVisible(true);
    }//GEN-LAST:event_viewRecordsActionPerformed

    private void updateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDetailsActionPerformed
        BuyerEditDetails e = new BuyerEditDetails(buyer);
        this.setVisible(false);
        e.setVisible(true);
    }//GEN-LAST:event_updateDetailsActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        Login l = new Login();
        this.setVisible(false);
        l.setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        welcomeLabel.setText("Welcome" + " " + buyer.getName() + ", " + "Your Rating is:" + " " + buyer.getRating());

    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton logout;
    private javax.swing.JButton purchaseItem;
    private javax.swing.JButton updateDetails;
    private javax.swing.JButton viewItemsOnSale;
    private javax.swing.JButton viewRecords;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
